-- Creating the table for loading the data set through the load data infile local method ( Environment variables are to be set for this)
CREATE TABLE prosperloandata_temp (
    ListingKey VARCHAR(255) PRIMARY KEY,
    ListingNumber BIGINT,
    ListingCreationDate date,
    CreditGrade VARCHAR(255),
    Term INT,
    LoanStatus VARCHAR(255),
    ClosedDate date,
    BorrowerAPR DECIMAL(15, 10),
    BorrowerRate DECIMAL(15, 10),
    LenderYield DECIMAL(15, 10),
    EstimatedEffectiveYield DECIMAL(15, 10),
    EstimatedLoss DECIMAL(15, 10),
    EstimatedReturn DECIMAL(15, 10),
    ProsperRatingNumeric INT,
    ProsperRatingAlpha VARCHAR(255),
    ProsperScore INT,
    ListingCategoryNumeric INT,
    BorrowerState VARCHAR(255),
    Occupation VARCHAR(255),
    EmploymentStatus VARCHAR(255),
    EmploymentStatusDuration INT,
    IsBorrowerHomeowner BOOLEAN,
    CurrentlyInGroup BOOLEAN,
    GroupKey VARCHAR(255),
    DateCreditPulled date,
    CreditScoreRangeLower INT,
    CreditScoreRangeUpper INT,
    FirstRecordedCreditLine date,
    CurrentCreditLines INT,
    OpenCreditLines INT,
    TotalCreditLinesPast7Years INT,
    OpenRevolvingAccounts INT,
    OpenRevolvingMonthlyPayment DECIMAL(15, 2),
    InquiriesLast6Months INT,
    TotalInquiries INT,
    CurrentDelinquencies INT,
    AmountDelinquent DECIMAL(15, 2),
    DelinquenciesLast7Years INT,
    PublicRecordsLast10Years INT,
    PublicRecordsLast12Months INT,
    RevolvingCreditBalance DECIMAL(15, 2),
    BankcardUtilization DECIMAL(15, 2),
    AvailableBankcardCredit DECIMAL(15, 2),
    TotalTrades INT,
    TradesNeverDelinquent DECIMAL(5, 2),
    TradesOpenedLast6Months INT,
    DebtToIncomeRatio VARCHAR(255),
    IncomeRange VARCHAR(255),
    IncomeVerifiable BOOLEAN,
    StatedMonthlyIncome DECIMAL(15, 2),
    LoanKey VARCHAR(255),
    TotalProsperLoans INT,
    TotalProsperPaymentsBilled INT,
    OnTimeProsperPayments INT,
    ProsperPaymentsLessThanOneMonthLate INT,
    ProsperPaymentsOneMonthPlusLate INT,
    ProsperPrincipalBorrowed DECIMAL(15, 2),
    ProsperPrincipalOutstanding DECIMAL(15, 2),
    ScorexChangeAtTimeOfListing INT,
    LoanCurrentDaysDelinquent INT,
    LoanFirstDefaultedCycleNumber INT,
    LoanMonthsSinceOrigination INT,
    LoanNumber INT,
    LoanOriginalAmount DECIMAL(15, 2),
    LoanOriginationDate date,
    LoanOriginationQuarter VARCHAR(255),
    MemberKey VARCHAR(255),
    MonthlyLoanPayment DECIMAL(15, 2),
    LP_CustomerPayments DECIMAL(15, 2),
    LP_CustomerPrincipalPayments DECIMAL(15, 2),
    LP_InterestandFees DECIMAL(15, 2),
    LP_ServiceFees DECIMAL(15, 2),
    LP_CollectionFees DECIMAL(15, 2),
    LP_GrossPrincipalLoss DECIMAL(15, 2),
    LP_NetPrincipalLoss DECIMAL(15, 2),
    LP_NonPrincipalRecoveryPayments DECIMAL(15, 2),
    PercentFunded DECIMAL(15, 2),
    Recommendations INT,
    InvestmentFromFriendsCount INT,
    InvestmentFromFriendsAmount DECIMAL(15, 2),
    Investors INT
);

-- Loading the data using the data local infile option from .csv file
LOAD DATA LOCAL INFILE 'C:/Users/Sravya/Desktop/FinancialDataAnalysis/prosperLoanData.csv' INTO TABLE prosperLoanData_temp FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

-- Fetching the data from the data file.
Select * from prosperLoanData_temp;
